services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Koehnlein\Falduplicates\:
    resource: '../Classes/*'

  Koehnlein\Falduplicates\Command\FindDuplicates:
    tags:
      - name: 'console.command'
        command: 'falduplicates:find'
